### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by dan-gill** [ViktorJp/VPNMON-R2#1]
You have a typo in the README.md for screen. You have `screen -dmS vpnmonr2 sh /jffs/scripts/vpnmon-r2.sh -monitor` but it should be `screen -dmS vpnmon-r2 sh /jffs/scripts/vpnmon-r2.sh -monitor` based on the next command.

**Comment by ViktorJp** [comment]
You can actually call it whatever you like - that's the screen "name" you're giving it... I like to keep it simple without having to hit the dash, but you could even do something like this:

screen -dmS whatever sh /jffs/scripts/vpnmon-r2.sh -monitor

then call it with:

screen -d whatever

;)

**Comment by ViktorJp** [comment]
For consistency's sake, I'll change it "vpnmon-r2"... probably would make it less confusing.  ;)  Thanks again.
