### ISSUE TITLE
Adjustments Needed?

### ISSUE THREAD

**Issue by justinglock40** [ViktorJp/VPNMON-R2#2]
Afternoon,

Tried using this today via amtm, but I can't the script to complete because it shows the clients offline. Is this because I'm not using full tunnel? I only have traefik that's destined for a specific IP go through the VPN

**Comment by ViktorJp** [comment]
Hi... if it's showing that clients are off-line, that means your router is unable to ping the VPN Client Hosts you have configured in your various VPN Client slots.  I would look at resolving that first, and ensure that each slot is configured correctly, and that you can "switch on" each VPN client slot without it erroring out.  Hope that helps!?

**Comment by justinglock40** [comment]
If I turn on the switches myself. the connections work fine

**Comment by ViktorJp** [comment]
> If I turn on the switches myself. the connections work fine

It would be very odd for your VPN provider to block a ping to their own servers. Which VPN provider do you use?  Maybe I'm not understanding your environment, or how you have things setup?  Is there any way you can provide any screenshots, logs or information about how you set up your VPN slots?  I've made a rudimentary setup manual here that may help: https://www.snbforums.com/threads/vpnmon-r2-v2-11-aug-3-2022-monitor-your-vpn-connections-health-new-amtm-fastest-connection-switching-nord-surfshark-perfectprivacy-2.79762/post-776164

**Comment by ViktorJp** [comment]
No response after 3 weeks
