### ISSUE TITLE
Setup fails on XT8 (RT-AX95Q) (via vpnmon-r2.cfg)

### ISSUE THREAD

**Issue by gesa** [ViktorJp/VPNMON-R2#3]
Steps to reproduce:

0. from amtm: format disk, create swap, install entware
1. install VPNMON-R2
2. launch vpnmon using `vp` in amtm
3. select `sc` to set up and configure VPNMON-2

Expected result: run configuration process for VPNMON-2

Actual result: terminal cleared and replaced with `/jffs/scripts/vpnmon-r2.sh:/jffs/addons/vpnmon-r2.d/vpnmon-r2.cfg:line 64: syntax error: unterminated quoted string` (see screenshot)
![2303_61pu7](https://user-images.githubusercontent.com/782056/227744455-042e0960-16cd-45b8-8a32-545c3f50019b.jpeg)

**Comment by ViktorJp** [comment]
Great catch.  I've just published v2.49 which takes care of this unterminated quoted string -- my error! :)  Let me know if this works for you, and I'll close this case.  ;)

**Comment by gesa** [comment]
I had to uninstall and reinstall, but that process is straightforward and quick so nbd. That done, it worked perfectly!
